name: Build Firmware

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      BOARD_TYPE: PIMORONI_BADGER2040
      PIMORONI_PICO_PATH: $GITHUB_WORKSPACE/pimoroni-pico
    
    steps:

    - name: Set GITHUB_WORKSPACE
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        path: project

    - name: Import environment variables from a file
      id: import-env
      shell: bash
      run: |
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < "${{env.GITHUB_WORKSPACE}}/project/firmware/dependencies.env"
    
    - name: Workspace Cache Micropython
      id: cache-micropython-src
      uses: actions/cache@v3
      with:
        path: |
          ${{env.GITHUB_WORKSPACE}}/micropython
          ${{env.GITHUB_WORKSPACE}}/pimoroni-pico
        key: workspace-micropython-${{env.MICROPYTHON_VERSION}}-${{env.PIMORONI_VERSION}}
        restore-keys: |
          workspace-micropython-${{env.MICROPYTHON_VERSION}}-${{env.PIMORONI_VERSION}}

    - name: Compiler Cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.ccache
        key: ccache-compiler-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ccache-micropython-badger2040-${{github.ref}}
          ccache-micropython-badger2040-
    
    - name: Checkout Pimoroni Pico
      if: steps.cache-micropython-src.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: pimoroni/pimoroni-pico
        ref: ${{env.PIMORONI_VERSION}}
        path: pimoroni-pico
        submodules: true


    - name: Checkout Micropython
      if: steps.cache-micropython-src.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: micropython/micropython
        ref: ${{env.MICROPYTHON_VERSION}}
        path: micropython
        submodules: false

    - name: Fetch base MicroPython submodules
      if: steps.cache-micropython-src.outputs.cache-hit != 'true'
      shell: bash
      working-directory: micropython
      run: git submodule update --init

    - name: Fetch Pico SDK submodules
      if: steps.cache-micropython-src.outputs.cache-hit != 'true'
      shell: bash
      working-directory: micropython/lib/pico-sdk
      run: git submodule update --init
      
    - name: Build mpy-cross
      if: steps.cache-micropython-src.outputs.cache-hit != 'true'
      shell: bash
      working-directory: micropython/mpy-cross
      run: make
      
    - name: "HACK: MicroPython Board Fixups"
      if: steps.cache-micropython-src.outputs.cache-hit != 'true'
      shell: bash
      working-directory: micropython/ports/rp2
      run: |
        ${{env.PIMORONI_PICO_PATH}}/micropython/_board/board-fixup.sh badger2040 ${{env.BOARD_TYPE}} ${{env.PIMORONI_PICO_PATH}}/micropython/_board      
      
    - name: Install Compiler & CCache
      run: |
        sudo apt update && sudo apt install ccache gcc-arm-none-eabi
        python3 -m pip install pillow
    
    - name: Configure MicroPython Build
      shell: bash
      working-directory: micropython/ports/rp2
      run: |
        cmake -S . -B build-${{env.BOARD_TYPE}}-without-badger-os -DPROJ_DIR=$GITHUB_WORKSPACE/project -DPIMORONI_PICO_PATH=${{env.PIMORONI_PICO_PATH}} -DPICO_BUILD_DOCS=0 -DUSER_C_MODULES=$GITHUB_WORKSPACE/project/firmware/firmware.cmake -DMICROPY_BOARD=${{env.BOARD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build MicroPython
      shell: bash
      working-directory: micropython/ports/rp2
      run: |
        ccache --zero-stats || true
        cmake --build build-${{env.BOARD_TYPE}}-without-badger-os -j 2 -v
        ccache --show-stats || true
        
    - name: Store .uf2 as artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.uf2
        path: micropython/ports/rp2/build-${{env.BOARD_TYPE}}-without-badger-os/firmware.uf2
