name: Build Firmware

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      MICROPYTHON_VERSION: 9dfabcd6d3d080aced888e8474e921f11dc979bb
      BOARD_TYPE: PIMORONI_BADGER2040
      PIMORONI_PICO_PATH: $GITHUB_WORKSPACE/pimoroni-pico
  
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        path: project

    - name: Checkout Pimoroni Pico
      uses: actions/checkout@v2
      with:
        repository: pimoroni/pimoroni-pico
        ref: v1.19.10
        path: pimoroni-pico

    - name: Checkout Micropython
      uses: actions/checkout@v2
      with:
        repository: micropython/micropython
        ref: ${{env.MICROPYTHON_VERSION}}
        path: micropython
        submodules: false

    - name: Fetch base MicroPython submodules
      shell: bash
      working-directory: micropython
      run: git submodule update --init

    - name: Fetch Pico SDK submodules
      shell: bash
      working-directory: micropython/lib/pico-sdk
      run: git submodule update --init
      
    - name: Fetch Pimoroni Pico submodules
      shell: bash
      working-directory: pimoroni-pico
      run: git submodule update --init

    - name: Build mpy-cross
      shell: bash
      working-directory: micropython/mpy-cross
      run: make
      
    - name: "HACK: MicroPython Board Fixups"
      shell: bash
      working-directory: micropython/ports/rp2
      run: |
        ${{env.PIMORONI_PICO_PATH}}/micropython/_board/board-fixup.sh badger2040 ${{env.BOARD_TYPE}} ${{env.PIMORONI_PICO_PATH}}/micropython/_board      
      
    - name: Install Compiler & CCache
      run: |
        sudo apt update && sudo apt install ccache gcc-arm-none-eabi
        python3 -m pip install pillow
    
    - name: Configure MicroPython Build
      shell: bash
      working-directory: micropython/ports/rp2
      run: |
        cmake -S $GITHUB_WORKSPACE/project/firmware -B build-${{env.BOARD_TYPE}}-without-badger-os -DMAKE_SOURCE_DIR=$GITHUB_WORKSPACE/micropython/ports/rp2 -DBADGER2040_NO_MODULES=1 -DPICO_BUILD_DOCS=0 -DUSER_C_MODULES=${{env.PIMORONI_PICO_PATH}}/micropython/modules/badger2040-micropython.cmake -DMICROPY_BOARD=${{env.BOARD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build MicroPython
      shell: bash
      working-directory: micropython/ports/rp2
      run: |
        ccache --zero-stats || true
        cmake --build build-${{env.BOARD_TYPE}}-without-badger-os -j 2 -v
        ccache --show-stats || true
        
    - name: Store .uf2 as artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.uf2
        path: micropython/ports/rp2/build-${{env.BOARD_TYPE}}-without-badger-os/firmware.uf2
